(in-package :ttf-examples)

(require 'sdl2-ttf)

(defun basic-example ()
  (with-init (:everything)
    ;;Technically speaking sdl2-ttf can be initialized without sdl2 
    (sdl2-ttf:init)
    (with-window (the-window :title "Basic Font Example" :w 300 :h 300 :flags '(:shown))
      (let* ((font (sdl2-ttf:open-font (sdl2-ttf:open-font (asdf:system-relative-pathname 'cl-sdl2-ttf-examples "PROBE_10PX_OTF.otf" 10))))))
      (with-renderer (my-renderer the-window :flags '(:accelerated))
        (let ((my-rect (make-rect 100 100 40 40)))
          (flet ((square-renderer (renderer)
                   (set-render-draw-color renderer 255 255 255 0)
                   (render-fill-rect renderer my-rect))
                 (clear-renderer (renderer)
                   (set-render-draw-color renderer 0 0 0 255)
                   (render-clear renderer)))
            (with-event-loop (:method :poll)
              (:idle ()
                     (clear-renderer my-renderer)
                     (square-renderer my-renderer)
                     (render-present my-renderer))
              (:quit ()
                     (when (> (sdl2-ttf:was-init) 0)
                       (sdl2-ttf:close-font font)
                       (sdl2-ttf:quit))
                     t))))))))
