(in-package :ttf-examples)

(defun basic-example ()
  (with-init (:everything)
    (with-window (the-window :title "Basic Font Example" :w 100 :h 100 :flags '(:shown))
      (with-renderer (my-renderer the-window :flags '(:accelerated))
        (flet ((clear-renderer (renderer)
                 (progn (set-render-draw-color renderer 0 0 0 255)
                        (render-clear renderer))))
          (with-event-loop (:method :poll)
            (:idle ()
                   (clear-renderer my-renderer)
                   (render-present my-renderer))
            (:quit ()
                   t)))))))
